#安装docker
# curl -sSL https://get.daocloud.io/docker | sh
# systemctl enable docker.service
# systemctl start  docker.service
#安装docker compose
# curl -L https://get.daocloud.io/docker/compose/releases/download/v2.4.1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
# sudo chmod +x /usr/local/bin/docker-compose
# sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
#启动命令 docker-compose --compatibility -f docker-compose-standalone.yaml up -d
version: '3.2'
networks:
  fb:
services:
  work:
    image: ccr.ccs.tencentyun.com/flowback/work
    environment:
      NETTY_SERVER_HOST: 10.206.16.3
      NETTY_SERVER_PORT: 22222
      JAVA_OPTS: "
                -Dfile.encoding=utf-8
                -Xmx4G
       "
    networks:
      - fb
  work2:
    image: ccr.ccs.tencentyun.com/flowback/work
    environment:
      NETTY_SERVER_HOST: 10.206.16.3
      NETTY_SERVER_PORT: 22222
      JAVA_OPTS: "
                -Dfile.encoding=utf-8
                -Xmx4G
       "
    networks:
      - fb