version: '3.2'
networks:
  monitor:
services:
  my_exporter_node:
    image: prom/node-exporter
    restart: always
    volumes:
      - /:/host:ro,rslave
    ports:
      - "9100:9100"
    networks:
      - monitor
  prometheus:
    image: prom/prometheus
    restart: always
    volumes:
      #路径为monitor目录下
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitor
  my_grafanar_node:
    image: grafana/grafana
    restart: always
    ports:
      - "3000:3000"
    networks:
      - monitor